# Generated by Django 4.1.4 on 2022-12-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spitz", "0003_spitz_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMapModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("url", models.CharField(max_length=140)),
                ("date", models.DateField()),
            ],
        ),
    ]
