# Generated by Django 4.1.4 on 2022-12-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spitz", "0004_sitemapmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteMapModel",
        ),
    ]
