# Generated by Django 4.1.4 on 2022-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spitz", "0005_delete_sitemapmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="spitz",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="typesspitz",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
